### ISSUE TITLE
Addon requires new account

### ISSUE THREAD

**Issue by JReissmueller** [blesta/module-cwatch#15]
One very important use case for the module is using it as an addon to other services.  If you want to have it as an addon for multiple services, you currently need a new cWatch account to be created for each addon.  That is not very reasonable or practical.

A unique account is currently required for each service because we don't want two different people creating a service with the same email and then being able to log in and manage each others domains.  Perhaps there is some solution that allows you to use the same email if you already have a cwatch service using it.

**Comment by tysonphillips** [comment]
>One very important use case for the module is using it as an addon to other services. If you want to have it as an addon for multiple services, you currently need a new cWatch account to be created for each addon. That is not very reasonable or practical.

You may want to make use of Blesta's module client meta data (i.e. ModuleClientMeta model) in this case. You should be able to assign a single reference to the client's account for the module and use it for each service.

> A unique account is currently required for each service because we don't want two different people creating a service with the same email and then being able to log in and manage each others domains. Perhaps there is some solution that allows you to use the same email if you already have a cwatch service using it.

Does cWatch not separate accounts properly? I would expect a service to be associated with a cWatch account, not a particular email address that anyone can use.

**Comment by JReissmueller** [comment]
Good idea.

No, every api call is by email.
